services:
  jobmanager:
    image: flink:1.20.0
    container_name: flink-jobmanager
    networks:
      - flink-network
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
        - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager   

  taskmanager:
    image: flink:1.20.0
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    networks:
      - flink-network
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2  
    command: taskmanager
    scale: 1

networks:
  flink-network:
    driver: bridge
