version: '2.2'

services:
  jobmanager:
    image: flink:latest
    ports:
      - "8081:8081"  # Exposes Flink's web dashboard on the default port
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        jobmanager.rpc.port: 6123
        jobmanager.memory.process.size: 1600m
    volumes:
      - jobmanager-data:/opt/flink/log  # Mounts a volume for logs

  taskmanager:
    image: flink:latest
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        taskmanager.memory.process.size: 1728m
    volumes:
      - taskmanager-data:/opt/flink/log  # Mounts a volume for logs

volumes:
  jobmanager-data:  # Declares a volume for the JobManager logs
  taskmanager-data:  # Declares a volume for the TaskManager logs
